version: "3.8"

services:

  #Postgres Database
  profile_db:
    image: postgres:16
    container_name: postgres_profile_container
    environment:
      POSTGRES_DB: profile_db
      POSTGRES_USER: profile_user
      POSTGRES_PASSWORD: profile_user123
    volumes:
      - postgres_profile_data:/var/lib/postgresql/data

  #Django Appication
  profile-backend:
    build: 
      context: ./server/user-profile
      dockerfile: Dockerfile
    image: profile-backend:user-profile
    container_name: profile_backend_container
    command: sh -c "chmod +x /user-profile/migrate.sh && chmod +x /user-profile/entrypoint.sh && sh /user-profile/migrate.sh && /user-profile/entrypoint.sh"
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - .:/user-profile
    depends_on:
      - profile_db

  #frontend
  # profile-frontend:
  #   container_name: profile_frontend_container
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - .:/profile-frontend

volumes:
  profile_backend_data:
  postgres_profile_data: